### ISSUE TITLE
Filename XSS Payload

### ISSUE THREAD

**Issue by beardog108** [webtorrent/instant.io#132]
Hi @feross, I love instant.io & WebTorrent.

Instant.io does not sanitize filenames within torrents, therefore a file named something like: `<img src=t onerror='alert('payload');' alt='XSS!'>.txt` could be used to deliver XSS.

Not a huge deal in the case of instant.io, but should still be fixed :sweat_smile:

**Comment by feross** [comment]
Thanks for reporting this issue. Since there's no site cookie or login info that an attacker could steal, the damage is limited, but you're right that this should be fixed.

**Comment by rugk** [comment]
Any news? When running instant.io on a domain with other web applications installed, this could have a more serious impact, so please fix it.

**Comment by feross** [comment]
I haven't had time to work on this, but if you want to send a PR that solves the issue, I'm happy to merge it.

**Comment by fengkx** [comment]
It seems to be fixed. https://github.com/webtorrent/instant.io/blob/master/client/index.js#L185

**Comment by beardog108** [comment]
The payload I used back then does not work anymore, so it does indeed appear to be fixed. I'll close this and someone can reopen if they find another way.

**Comment by feross** [comment]
thanks!
