### ISSUE TITLE
feature: "Download with WebTorrent" badge

### ISSUE THREAD

**Issue by wmhilton** [webtorrent/instant.io#141]
Take the power of WebTorrent, wrap it in a sexy looking button so all the cool kids want to add it to their README files, and take over the world...

![image](https://cloud.githubusercontent.com/assets/587740/24690591/d5fbec12-199b-11e7-8bdd-caf6e13a8609.png)

**Comment by feross** [comment]
I think this idea is cool, but I don't have the time to build it myself :)

**Comment by wmhilton** [comment]
I'm working on it...

**Comment by wmhilton** [comment]
Funny. That took a good bit longer to make than I expected...

https://wmhilton.com/download-with-webtorrent-button/

If you like it, I will polish the edges and document how to use it. But the gist is:
```html
<link rel="stylesheet" href="path/to/the/index.css">
<a class="webtorrent-download" href="fallback/download/path" data-torrent="torrentid">Link Text</a>
<script src="https://unpkg.com/webtorrent/webtorrent.min.js"></script>
<script src="path/to/the/script.js"></script>
```

**Comment by feross** [comment]
Super cool!

**Comment by wmhilton** [comment]
Random aside: PhantomJS doesn't support linear gradients whereas Electron does. So while `pageres` let me down, `nightmare` and `gifencoder` worked great for scripting this graphic:

![animated gif of button](https://github.com/wmhilton/download-with-webtorrent-button/raw/master/dist/animated.gif?raw=true)

**Comment by wmhilton** [comment]
There two things I want to try to do before I make a big noise about this. 1) I still need to put it on npm. The documentation is a lie. :) and 2) I want to see about automating the .torrent file creation. I don't think I can completely decentralize it but I ought to be able to make it an API call, and then people could use that service in the backend of their dynamic sites or in their static site build pipeline.

**Comment by feross** [comment]
@wmhilton It would be awesome if you got rid of the need for the `<style>` tag and the the WebTorrent `<script>` tag. That functionality could be included inside `script.js`. Then you could just do:

```html
<script src="script.js"></script>
<a href="https://example.com/node.pkg" data-torrent="magnet: ...">Download Node.js</a>
```

There's also no need for the `"webtorrent-download"` class, since you can actually use the presence of a `data-torrent` attribute as a selector in CSS.

This is actually really elegant!

**Comment by feross** [comment]
Btw, I just found this site: http://www.extratown.com/webtorrent No idea if it works well or not

**Comment by wmhilton** [comment]
> @wmhilton It would be awesome if you got rid of the need for the <style> tag and the the WebTorrent <script> tag. That functionality could be included inside script.js.

I've thought about that. I really like the appeal of "just add a single line of code to your site and it Just Works TM". The potential downsides are the FOUC and tying it to a bundled version of WebTorrent instead of getting the latest and greatest version. I *suppose* I could get around that second one by loading WebTorrent dynamically...

    // pseudo jQuery
    $.getScript('https://unpkg.com/webtorrent/webtorrent.min.js').then( (err) => ...

But then that delays fetching it until the button script is downloaded parsed and executed, adding unnecessary latency. But since the library doesn't depend on WebTorrent being loaded until the link is clicked... it could work. I just don't want to get TOO magical or people will struggle to understand it.

That's the other reason for bundling the CSS separately. Doing it with "CSS in JS" magic fancypants WebPack magic hides what's actually happening, while being all like "here's the CSS file... if you want to restyle the button to match your site just look at it and override rules or copy/paste it in your own style.css and directly mod it."

That being said, I am open to suggestions for improvement!

> There's also no need for the "webtorrent-download" class, since you can actually use the presence of a data-torrent attribute as a selector in CSS.

Great idea! It indeed uses `a[data-torrent]` as the style selector now. 😀

> This is actually really elegant!

Aw, thanks!

**Comment by wmhilton** [comment]
I made it even better (I think). You can now do:

    <a href="https://example.com/foobar.tar.gz" data-torrent="auto">Link</a>

And it will replace your data-torrent value like so:

    data-torrent="https://webtorrentify.now.sh?href=https://example.com/foobar.tar.gz">Link</a>

which auto-generates a .torrent file on the fly. It is probably not a first - there's plenty of prior art, notably BurnBit (which is gone?) and http://www.urlhash.com/ (which didn't add WebTorrent trackers) and now this extratown.com. But I believe it's the first that lends itself well to this kind of blind, automatic use rather than one-off "drag and drop a file on me" use. It memoizes its responses so if used as intended (repeatedly for the same download link) it should only be slow the first time. In theory, the server is probably incredibly weak to a DOS attack... but in practice, I don't think there exists an incentive for anyone to do so.

**Comment by feross** [comment]
@wmhilton Very nice work! Let me know when you have a landing page for this, or even a GitHub readme and we can add it to the list of projects that use WebTorrent and I'll tweet it from the @WebTorrentApp Twitter account!!

**Comment by wmhilton** [comment]
I'm trying to get it working for downloading nodejs... I thought I nearly had it working this evening using https://github.com/wmhilton/cors-buster But then apparently the Range headers weren't making it through... not sure if error lies in `node-fetch` or between chair and keyboard. I'll have to give it another shot this weekend.

If I wasn't so set on a General Solution, I'd have just mirrored all of nodejs and be seeding it by now, lol.

**Comment by feross** [comment]
@wmhilton Remember that if you set Range headers, an OPTIONS request will be sent before any GET requests. Just a thought... you might want to confirm that it's getting sent.

**Comment by wmhilton** [comment]
I wasn't forwarding enough headers. :) It works now.

See if the button works for you. Open the button page in Chrome and in Firefox, start one download first, and then when you start the other download you should see it go much faster because its transferring browser-to-browser. Or at least that's how I've been testing it.

https://wmhilton.com/download-with-webtorrent-button/

I have everything published on Github and NPM and now.sh, so if the button works on your machine, you have my blessing to...

![Share on All the places](https://cdn.meme.am/cache/instances/folder705/500x/76620705/x-all-the-things-share-on-all-the-places.jpg)

**Comment by feross** [comment]
Will tweet it out from the WebTorrentApp account again 👍

**Comment by wmhilton** [comment]
Hang on, I just had an epiphany. (But simultaneously am confused why I started this thread in instant.io instead of webtorrent.io)
