### ISSUE TITLE
fails to load unsafe scripts in chrome

### ISSUE THREAD

**Issue by scheng123** [webtorrent/instant.io#143]
It doesn't load "HTTP" torrents, it just says that it is downloading at 0kbs, infinity years, Any help will be appreciated

**Comment by feross** [comment]
Unfortunately, an HTTPS site can't make requests to an HTTP site. The browser prevents those requests since it would violate user expectations. You can workaround this by downloading the .torrent file and drag-dropping it onto the page!

**Comment by scheng123** [comment]
That is what I did

**Comment by scheng123** [comment]
ANd it still says load unsafe scripts

**Comment by feross** [comment]
Can you take a look at the Network Tab of Developer Tools and see if you can find out what URL it is trying to request?
