### ISSUE TITLE
broken JS delivery on instant.io

### ISSUE THREAD

**Issue by milankragujevic** [webtorrent/instant.io#144]
GET https://instant.io/bundle.js net::ERR_INCOMPLETE_CHUNKED_ENCODING

**Comment by FlaggedBrad** [comment]
I am getting the same error. Also, it seems like the bundle.js file has an infinite loading time when trying to open the [direct link](https://instant.io/bundle.js) in my browser. 
![image](https://cloud.githubusercontent.com/assets/18545011/26568676/210782c2-44ba-11e7-8354-f8ae74cfe8ba.png) 
![image](https://cloud.githubusercontent.com/assets/18545011/26568683/3119a4e2-44ba-11e7-8277-816d05ac1194.png)

**Comment by feross** [comment]
Thanks for posting this issue. It's resolved now. The webtorrent.io server had run out of disk space. I only had log rotation set up for the node.js server logs. I'm setting it up for the nginx logs as well now. Cheers!
