### ISSUE TITLE
iOS 11 support 

### ISSUE THREAD

**Issue by willwhitney** [webtorrent/instant.io#145]
Now that iOS 11 supports WebRTC it should be possible to play videos on instant.io, and indeed the demo on https://webtorrent.io works on an updated iPad.

However on instant.io, the page says it’s downloading but never shows the video. Bandwidth usage is high for a couple of minutes but then drops to zero.

**Comment by feross** [comment]
Worked for me once or twice in desktop Safari but it seems inconsistent. Sometimes it doesn't connect to any peers. It's not clear if this is because they're still ironing out bugs in the implementation. Let's keep an eye on it and take another look once the new Safari is actually released.

**Comment by m-brian** [comment]
@feross Apple is about to release iOS 11. What's your take on this issue now?

**Comment by willwhitney** [comment]
Ping! Everything is publicly released and the first bugs patched. Any interest in making moves here?

**Comment by si458** [comment]
Any update on if it works with iOS 11?

**Comment by feross** [comment]
The underlying simple-peer library was just updated to support iOS 11 and Safari 11, so https://instant.io will get the fix when I publish a new version later today.

**Comment by feross** [comment]
Just deployed and confirmed that it works.

https://instant.io

**Comment by Ciao121** [comment]
I'm not sure is relatad to this isssue (if not I'm sorry).
I'm getting this on instant.io using Safari 11.

![safari](https://user-images.githubusercontent.com/14965015/36474855-bf437a3c-16f0-11e8-93d2-38fdc244c406.jpg)

But as soon as the FULL video is downloaded it is possible to play it.

**Comment by feross** [comment]
@Ciao121 This is due to https://github.com/jhiesey/videostream/issues/24

**Comment by k0a1a** [comment]
hi, what's the right way of implementing this with webtorrent browser client? tnx
