### ISSUE TITLE
instant.io does not work behind a ReverseProxy in a subdirectory [apache]

### ISSUE THREAD

**Issue by nodiscc** [webtorrent/instant.io#147]
Hello, I host instant.io behind an apache reverse proxy. 

The configuration is the following:

```
$ cat /etc/apache2/conf-enabled/instantio.conf
LoadModule proxy_module /usr/lib/apache2/modules/mod_proxy.so
LoadModule proxy_http_module /usr/lib/apache2/modules/mod_proxy_http.so

#ProxyRequests On
#ProxyPreserveHost Off

<Proxy *>
    Order Allow,Deny
    Allow from all
</Proxy>

ProxyPass /instantio http://localhost:4000
ProxyPassReverse /instantio http://localhost:4000

Redirect 301 /transfer/ /instantio
```

The page loads but without any styling or working javascript. The browser console returns:

```
GET 
https://myvm.vm.lan/main.css [HTTP/1.1 404 Not Found 15ms]
GET 
https://myvm.vm.lan/logo.svg [HTTP/1.1 404 Not Found 12ms]
GET 
https://myvm.vm.lan/bundle.js [HTTP/1.1 404 Not Found 25ms]
```

How can I get instant.io to run in such a configuration?

I don't have a separate subdomain available to host instant.io. All my web services must live on the same domain.

Would it be possible to use relative paths to resources, instead of absolute paths?

Thanks

Edit: I'm beginning to think some HTTP headers are not passed correctly by apache.

**Comment by feross** [comment]
I think you might need to make the links to `main.css`, `bundle.js`, etc. into relative links if you're serving from a folder.
