### ISSUE TITLE
Can't download file being seeded

### ISSUE THREAD

**Issue by pmosse** [webtorrent/instant.io#150]
Hello,
I tried sharing a file through the drag&drop and the log looks like this:
Peers: 0 Progress: 100.0% Download speed: 0 B/s Upload speed: 0 B/s ETA: Done.
Then I tried downloading the file by using the magnet URI but it never starts the download (I am using Transmision in Ubuntu 16). It says "Downloading" and almost every tracker finds 1 peer but it remains like that.
Thanks!
Patricio

**Comment by feross** [comment]
From the [FAQ](https://webtorrent.io/faq):

> Why does browser downloading not work? I see no peers!
It does work! But you can't just use any random magnet uri or .torrent file. The torrent must be seeded by a WebRTC-capable client, i.e. WebTorrent Desktop, Vuze, webtorrent-hybrid, Playback, instant.io, or βTorrent.

> In the browser, WebTorrent can only download torrents that are explicitly seeded to web peers via a WebRTC-capable client. Desktop torrent clients need to support WebRTC to connect to web browsers.
