### ISSUE TITLE
Can't download file with web seeds

### ISSUE THREAD

**Issue by konradr25** [webtorrent/instant.io#151]
I try to download torrent with web seed, but I cannot. It doesn't connect with the web server. 
Here is the magnet:
`magnet:?xt=urn:btih:83291E6B8673F789710C123941E2F1C44E335323&dn=debian-9.1.0-amd64-xfce-CD-1.iso&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&ws=https%3a%2f%2fsaimei.ftp.acc.umu.se%2fdebian-cd%2fcurrent%2famd64%2fiso-cd%2fdebian-9.1.0-amd64-xfce-CD-1.iso`

And logs from console:
`Fetch API cannot load https://saimei.ftp.acc.umu.se/debian-cd/current/amd64/iso-cd/debian-9.1.0-amd64-xfce-CD-1.iso. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://instant.io' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by feross** [comment]
This error message "No 'Access-Control-Allow-Origin' header is present on the requested resource" means that the servers hosting the Debian download do not have the correct HTTP headers set on their HTTP responses to allow other domains like instant.io to access the file contents.
