### ISSUE TITLE
customize tracker setting

### ISSUE THREAD

**Issue by qqdaiyu55** [webtorrent/instant.io#155]
I want to deploy instant.io with my own tracker instead of the default tracker lists. Where to modify the tracker setting? Thanks!

**Comment by Nover2** [comment]
How did you solve it?

**Comment by qqdaiyu55** [comment]
@Nover2 yes I have solved it. I modified the tracker list which is located in the codebase of instant.io or webtorrent, I'm not sure about it since it's long long ago :)
You can search the tracker list variable with global search which is a part of modern IDE, e.g. VS Code.
