### ISSUE TITLE
Downloading from seed ok but error if using hash

### ISSUE THREAD

**Issue by Ciao121** [webtorrent/instant.io#166]
Downloading using https://webtorrent.io/torrents/sintel.torrent in thetorrent is working.
But trying the correnpondant infoHash (08ada5a7a6183aae1e09d831df6748d566095a10) seems not to work.

**Comment by feross** [comment]
When downloading using the .torrent file, you'll have a web seed which lets the browser download the file over HTTP. So it could be that you're unable to connect to any peers for some reason and the fallback to HTTP is why it works with the .torrent file.

One other thing to try is disabling your ad blocker, which may block the tracker servers that WebTorrent uses to find peers. Ad blockers think that the phrase "tracker" is related to ad tracking, unfortunately.
