### ISSUE TITLE
Seed even when tabs are closed 

### ISSUE THREAD

**Issue by Nashorn** [webtorrent/instant.io#167]
When the original seeder closes the tab and say 2 other seeders close their PC seeding stops.  If I wanted the file to seed contiously, what would be a good high level architecture? 

If I run my own instant. Io copy on server, will it so it

**Comment by feross** [comment]
If you want to always ensure that a file is available, take a look at Web Seeds. They're basically an HTTP server URL that will be used when there are few/no peers available.

**Comment by Nashorn** [comment]
Thanks Feros, i'll check into it and get back to this thread. Please don't close it yet.

**Comment by Nashorn** [comment]
OK, i could not for the life of me find a simple example of how to implement webseeds with webtorrent, this is currently a stumbling block on an app i am designing.

But i did find this and would like to know if this is out-of-date, if there is a better example pleaseee send 

WEB SEEDING :
https://hackernoon.com/how-to-create-a-swarm-cdn-for-free-with-webtorrent-bfa09d193f71

**Comment by feross** [comment]
You can create a torrent with the `create-torrent` command line program.

```bash
npm install create-torrent -g
create-torrent --urlList http://example.com/torrent-path --other-arguments
```

You can get info about all the other arguments with `create-torrent --help`, but the one you need is `--urlList` if you want to include a web seed in a torrent file. For magnet links, you add the `ws` url parameter, so add `&ws=http://example.com/torrent-path` to the end of the magnet link.

The URL that you point to should be a folder with the torrent contents. You can learn more by reading the web seed spec: http://www.bittorrent.org/beps/bep_0019.html

**Comment by Nashorn** [comment]
I installed and ran the cmd given, the cmd console shows what appears to be a magnet uri, but the .torrent file created is blank.

create-torrent --urlList 'http://localhost:3000/resources/video/timedrift-alpine-4k-timelapse.mp4' "timedrift.torrent"
d8:announce40:udp://tracker.leechers-paradise.org:696913:announce-listll40:udp://tracker.leechers-paradise.org:6969el34:udp://tracker.coppersurfer.tk:6969el33:udp://tracker.opentrackr.org:1337el23:udp://explodie.org:6969el31:udp://tracker.empire-js.us:1337el26:wss://tracker.btorrent.xyzel32:wss://tracker.openwebtorrent.comel25:wss://tracker.fastcast.nzee10:created by34:WebTorrent <https://webtorrent.io>13:creation datei1524694421e8:encoding5:UTF-84:infod6:lengthi0e4:name17:timedrift.torrent12:piece lengthi16384e6:pieces0:e8:url-listl71:http://localhost:3000/resources/video/timedrift-alpine-4k-timelapse.mp4eeROSELCDV0072761:FileShare

i've tried with the original url and same results:
create-torrent --urlList 'https://webseed.btorrent.xyz/timedrift-alpine-4k-timelapse.mp4' 'timedrift.torrent'

**Comment by Nashorn** [comment]
how hard would it be to modify the .seed() method to allow url's as well?

**Comment by feross** [comment]
When you run `create-torrent`, you need to specify an output file with the `-o` option or else the torrent file contents will appear on your Terminal.

You need something like this:

```
create-torrent /path/to/timedrift-alpine-4k-timelapse.mp4 --urlList 'http://localhost:3000/resources/video/timedrift-alpine-4k-timelapse.mp4' -o timedrift.torrent
```

**Comment by feross** [comment]
> how hard would it be to modify the .seed() method to allow url's as well?

`client.seed()` already supports `urlList` option and any options that [`create-torrent`](https://github.com/webtorrent/create-torrent) supports.

**Comment by Nashorn** [comment]
Duh
