### ISSUE TITLE
[Enhancement] Docker + Docker Compose support

### ISSUE THREAD

**Issue by dydx** [webtorrent/instant.io#173]
Working on "Dockerizing" this along with a Docker Compose configuration

I have a small roadmap to be eventually happy with this

- [x ] Base `Dockerfile` file
- [x ] Base `docker-compose.yml` file
- [ ] Migrate configuration items in `secret/index.js` to also reference environment variables
- [ ] Polish up `Dockerfile`
- [ ] Polish up `docker-compose.yml`

**Comment by feross** [comment]
I don't use Docker and personally don't see the value in it. If you want to PR instructions into the Readme, I'll merge those. But I don't want to include additional files in the repo that are not actually used by the official deployment of instant.io on https://instant.io.

**Comment by stevetuk71** [comment]
Do you still not see the value of Docker?

**Comment by feross** [comment]
Nope. I don't use it to deploy instant.io.

**Comment by stevetuk71** [comment]
Shame, it would probably increase the user base and likely promote your product further. Loving your work by the way!
