### ISSUE TITLE
Adding search?

### ISSUE THREAD

**Issue by sagar1garg** [webtorrent/instant.io#178]
@feross @joshterrill 

How can I add search in instant.io?? I mean how does search work here? Can I search with file name?

**Comment by joshterrill** [comment]
instant.io does not let you search for torrents, if that's what you're asking.

**Comment by piyushchauhan** [comment]
Can we make this app to keep track of all the torrents on a server and produce search results. I will be a very good enhancement I think. If this has been discussed in some issue, forgive me.

**Comment by feross** [comment]
Sorry, this is out of scope for instant.io. Feel free to make your own site that implements this.
