### ISSUE TITLE
[Security Request] Jackett Search Support

### ISSUE THREAD

**Issue by zero77** [webtorrent/instant.io#184]
At the moment you have to go and find all torrent or magnet links manually, to improve this, can you also add support for searching and adding torrents or magnets with Jackett.

“Jackett works as a proxy server: it translates queries from apps (Sonarr, Radarr, SickRage, CouchPotato, Mylar, DuckieTV, etc) into tracker-site-specific http queries, parses the html response, then sends results back to the requesting software. This allows for getting recent uploads (like RSS) and performing searches. Jackett is a single repository of maintained indexer scraping & translation logic - removing the burden from other apps”. https://github.com/Jackett/Jackett

Also, once Jackett support is implemented, all indexers are updated and maintained by the Jackett developers.

Thanks

**Comment by feross** [comment]
This is out of scope for this project. Thanks.
