### ISSUE TITLE
I can't get your bloody website to stop opening magnet links

### ISSUE THREAD

**Issue by dmeff** [webtorrent/instant.io#185]
Even after making my torrent client bind magnet links again.

How do I fix this?

**Comment by ganezdragon** [comment]
@dmeff , its the settings with your browser. For example, in firefox, we could change the behavior for magnetic links under Preferences,
<img width="984" alt="image" src="https://user-images.githubusercontent.com/10774943/49701145-8cfe0700-fc0e-11e8-8be7-e2b1fa083d4c.png">

**Comment by gslsqs** [comment]
try this.
chrome : settings/Advanced settings/Privacy and security: Content settings/Handlers

**Comment by gslsqs** [comment]
try this:
 chrome : settings/Advanced settings/Privacy and security: Content settings/Handlers

@dmeff

**Comment by feross** [comment]
You can configure which sites are registered as protocol handlers at this URL: `chrome://settings/handlers?search=handlers`

**Comment by vdbhb59** [comment]
> @dmeff , its the settings with your browser. For example, in firefox, we could change the behavior for magnetic links under Preferences, <img alt="image" width="984" src="https://user-images.githubusercontent.com/10774943/49701145-8cfe0700-fc0e-11e8-8be7-e2b1fa083d4c.png">

This is the only one that worked to at least remove instant.io bugging me. I had completely forgotten about it.
