### ISSUE TITLE
File length too large for Blob URL approach

### ISSUE THREAD

**Issue by alex2844** [webtorrent/instant.io#189]
![](https://user-images.githubusercontent.com/18526177/49451670-84b65e00-f801-11e8-90f1-d4fb4583754f.png)

Is limit set in webtorrent, or in a browser?

**Comment by feross** [comment]
This is a limit set by instant.io. It's configurable. We keep it set to 2GB for now since the full file has to be loaded into memory and we don't want to crash the browser tab. Once we have IndexedDB support added, then we can lift this limit.
