### ISSUE TITLE
Which Torrent site work this ?

### ISSUE THREAD

**Issue by lyricsbd** [webtorrent/instant.io#191]
I tried many torrent site link & magnet link but not work.It just work demo magnet file why?
any solution??????

**Comment by ivan386** [comment]
WebTorrent client connect to other WebTorrent clients that use WebRTC as trasport protocol. It can't connect to Bittorrent clients. But it can download data via http(s) if torrent or magnet contain webseed address.

**Comment by JeremyBenson11** [comment]
instant.io is one of the current promoted ways of uploading files.
