### ISSUE TITLE
Issue Uploading

### ISSUE THREAD

**Issue by JeremyBenson11** [webtorrent/instant.io#192]
I'm trying to upload a 125mb video on instant.io. I had success a day ago with a similar video. Both mp4s. This time the video shows up on the page, but when I click play I see error rending file undefined. Also it showed as uploaded fairly soon with no progress bar. This time I didn't see any movement in Upload speed: 0 B/s during what I thought was the seeding process the first time. The first works, even on my server with JS player. I'm not sure about this one.  I haven't tested the magnet yet on JS player. I'm just wondering about the undefined error and no movement in instant.io. Is something abnormal happening? I was thinking maybe a better progress meter on the site would be beneficial.

**Comment by feross** [comment]
This sounds like a bug but it's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue. A pull request to fix the bug would also be most welcome!
