### ISSUE TITLE
How can instant.io handle all the magnet links in my Chrome?

### ISSUE THREAD

**Issue by hugetiny** [webtorrent/instant.io#193]
Amazing.
Whenever I click a magnet link, Chrome always opens a tab and automatically start downloading in instant.io, I don't remember I installed any chrome extensions for instant.io.

**Comment by feross** [comment]
We ask to handle `magnet:` URLs using the [`registerProtocolHandler`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler) API.

**Comment by Starkemis** [comment]
It's a pain in the ass.
