### ISSUE TITLE
how to play videos types mkv using nodejs?

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [webtorrent/instant.io#194]
Hi,

I was creating an app using the npm thepiratebay that will help me get the magnetlinks to use them in webtorrent and play them in video.

The vast majority are in MKV video type.

My Doubt is:
How can I use this type of magnet in a video?

**Comment by jimmywarting** [comment]
Do not post links or references to copyrighted content in your issues.

**Comment by ChrisMichaelPerezSantiago** [comment]
regards,

Apologies, I'll be removing it.

**Comment by adamwoo2444** [comment]
@ChrisMichaelPerezSantiago  hey can you help me i am facing a similar issue.
Thanks.
