### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by loskiq** [webtorrent/instant.io#196]
why?
```
connection error to wss://tracker.fastcast.nz
connection error to wss://tracker.btorrent.xyz
connection error to wss://tracker.fastcast.nz
connection error to wss://tracker.fastcast.nz
connection error to wss://tracker.btorrent.xyz
```

**Comment by jimmywarting** [comment]
Maybe overloaded with traffic...
Would really love to see Web DHT some day. More reliable than a public tracker with limited resources.

**Comment by josephrocca** [comment]
Just a note to say that the errors are still occurring (in case it was thought to just be a temporary thing):

![image](https://user-images.githubusercontent.com/1167575/62004924-fbc4ac00-b16e-11e9-8116-03114e7b0b4d.png)

Seeing two types of errors:
 * 502 Bad Gateway
 * 522 Origin Connection Time-out

**Comment by urza** [comment]
I see similar error messages still as of 2019-11-29

connection error to wss://tracker.btorrent.xyz
connection error to wss://tracker.fastcast.nz
connection error to wss://tracker.btorrent.xyz
connection error to wss://tracker.fastcast.nz
connection error to wss://tracker.btorrent.xyz

**Comment by feross** [comment]
These types of messages happen anytime a tracker doesn't respond and they're not fatal. Nothing to fix here.
