### ISSUE TITLE
Error: Cannot find module '../secret'

### ISSUE THREAD

**Issue by PaTiToMaSteR** [webtorrent/instant.io#198]
Latest version of the repo, npm i and then npm start:

npm install
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 8742 packages in 7.633s
found 0 vulnerabilities

PS FOLDER\Git\instant.io-master> npm start

> instant.io@1.0.0 start FOLDER\Git\instant.io-master
> npm run build && node server

> instant.io@1.0.0 build FOLDER\Git\instant.io-master
> npm run build-css && npm run build-js

> instant.io@1.0.0 build-css FOLDER\Git\instant.io-master
> stylus css/main.styl -o static/ -c

  compiled static\main.css

> instant.io@1.0.0 build-js FOLDER\Git\instant.io-master
> browserify client | minify > static/bundle.js

internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '../secret'
Require stack:
- FOLDER\Git\instant.io-master\server\rollbar.js
- FOLDER\Git\instant.io-master\server\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (FOLDER\Git\instant.io-master\server\rollbar.js:3:36)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'G:\\Dropbox (Personal)\\Git\\instant.io-master\\server\\rollbar.js',
    'G:\\Dropbox (Personal)\\Git\\instant.io-master\\server\\index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! instant.io@1.0.0 start: `npm run build && node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the instant.io@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thepr\AppData\Roaming\npm-cache\_logs\2019-07-03T18_24_58_974Z-debug.log
PS FOLDER\Git\instant.io-master>

**Comment by PaTiToMaSteR** [comment]
Sorry I jumped a step of the readme: 
Copy secret/index-sample.js to secret/index.js and set the Twilio API key if you want a NAT traversal service (to help peers connect when behind a firewall).

To start the server, run npm start. That should be it!

**Comment by adamwoo2444** [comment]
@PaTiToMaSteR hey can you help me out I am facing an issue while setting up instant.io on my local machine.
Thank you :D

**Comment by PaTiToMaSteR** [comment]
@adamwoo2444 I couldn’t make the same sample work in my machine because instant.io use a service to open ports through CG NAT, etc. webtorrent doesn’t have the same ability. You can easily implement upnp, but is not enough.

@feross might clarify more about this than I can

**Comment by feross** [comment]
Using Twilio is not required. If you remove the code that does that from instant.io, it should still work. Just less likely to be able to connect peers in all instances.

**Comment by hzh003** [comment]
@feross can u pls tell me where to remove the code that use twilio? thanks

**Comment by adamwoo2444** [comment]
server->index.js line no 103 to 147 .
Hope it helps. Let me know If you have any question.
