### ISSUE TITLE
Instant.io is not working!

### ISSUE THREAD

**Issue by adamwoo2444** [webtorrent/instant.io#201]
I have tried to run instant.io on localhost. But its not working. I have changed the config file.
This is my config file.I have also updated its tracker list. Any lead how I can run on localhost.
It is compiling but not working/downloading/streaming anything.
```
/**
 * Is site running in production?
 */
exports.isProd = process.env.NODE_ENV === 'production'
exports.port = 7010;
```

**Comment by adamwoo2444** [comment]
my updated trackerlist
```
   ["udp://tracker.coppersurfer.tk:6969"],
                ["udp://tracker.pirateparty.gr:6969"],
                ["udp://tracker.internetwarriors.net:1337"],
                ["udp://tracker.opentrackr.org:1337"],
                ["udp://9.rarbg.to:2740"]
```

**Comment by adamwoo2444** [comment]
okay done.

**Comment by borekon** [comment]
> okay done.

Could you explain what you've done?
