### ISSUE TITLE
Add torrent through URL

### ISSUE THREAD

**Issue by t9999clint** [webtorrent/instant.io#209]
I can't find any good documentation on how to use this site.
I love the project, and it has worked very well with the limited testing I have done with it.

Anyways I have two simple questions. I want to share a custom raspberry pi image with a number of users. I would like to use your site to help out with this. 

Question one: Is there a way for me to create a link (https://instant.io/URL_TO_TORRENT_FILE) that will automatically start a download using the url of the .torrent file hosted on my webserver? magnet link would also be ok.

The other question is this, what is the maximum filesize that can be used with instant.io?

I apologize in advance if these questions have already been answered.

**Comment by feross** [comment]
> Is there a way for me to create a link (instant.io/URL_TO_TORRENT_FILE) that will automatically start a download using the url of the .torrent file hosted on my webserver? magnet link would also be ok.

Yes, this works. See: https://instant.io/#https://webtorrent.io/torrents/sintel.torrent You need to ensure your website has the proper CORS headers to allow instant.io to download and use the torrent file. Usually this is just the following HTTP header: `access-control-allow-origin: *`

> what is the maximum filesize that can be used with instant.io?

Any size should work, but the file is kept in memory in the browser, so ideally it wouldn't be more than ~4GB.
