### ISSUE TITLE
instant.io hijacking my default association for .torrent and .magnet links

### ISSUE THREAD

**Issue by menriquez** [webtorrent/instant.io#214]
**What version of this package are you using?**
i dont know
**What operating system, Node.js, and npm version?**
win10
**What happened?**
instant.io always comes up to start downloading my torrents even after i reset my default association in windows back to my regular torrent desktop app
**What did you expect to happen?**
instant.io to go away and never come back
**Are you willing to submit a pull request to fix this bug?**
no

Please tell me what i need to do get rid of instant.io!!  this is rediculous your software should NOT override the win10 defaults with opening .torrent and .magnet files thats TERRIBLE behavior!!  i can't even figure out how to get rid of it or why its even happening because i don't see a chrome extension to get rid or or anything ...so its just plain RUDE your stuff is doing this!!

**Comment by jasondonnette** [comment]
I just ran into this myself and all I did was visit the site earlier. It shouldn't be hijacking magnet links like this without permission. (I am surprised chrome didn't ask permission - feels like a Chrome bug as well)

Assuming you're on Chrome, I fixed it by removing it from: [chrome://settings/handlers](url)

**Comment by feross** [comment]
Sorry that this happened for you. Browsers show a permission prompt for this functionality: 

<img width="500" alt="Screen Shot 2020-07-16 at 8 34 46 PM" src="https://user-images.githubusercontent.com/121766/87745862-e98ab600-c7a3-11ea-8cfa-8cac7be9bd3d.png">

I assume this was some kind of browser bug or perhaps you clicked "Allow" by mistake.
