### ISSUE TITLE
"Unsupported file type ... .xz ... Cannot append to DOM"

### ISSUE THREAD

**Issue by mxmilkiib** [webtorrent/instant.io#223]
**What version of this package are you using?**

The live demo service

**What operating system, Node.js, and npm version?**

Arch Linux, Firefox

**What happened?**

![image](https://user-images.githubusercontent.com/108225/82103586-7b763400-970b-11ea-9f4e-0c61e8ffbd97.png)

**What did you expect to happen?**

No error.

**Comment by tsonge** [comment]
Instant.io tries to display the file that you just uploaded/downloaded directly on the web page by "appending it to the DOM". Stuff like images/videos works (you can try it), but obviously your .tar.xz file doesn't. So the error is expected.

**Comment by mxmilkiib** [comment]
Aha, thanks for the clarification :)

Maybe there is worth in having an "Displaying file in browser.." or similar message?
