### ISSUE TITLE
https://instant.io/ please help me

### ISSUE THREAD

**Issue by GabrielAssisCode** [webtorrent/instant.io#228]
Can you create a past here with the files as working at "https://instant.io/", the examples here are not complete and not working....
Please...thanks

**Comment by GabrielAssisCode** [comment]
Put only the html and javascript necessary to work as in oficial website

**Comment by GabrielAssisCode** [comment]
You have done a very good job, thanks for sharing

**Comment by GabrielAssisCode** [comment]
If you put the complete code and only the files needed in 1 folder... only ".html" and ".js" will help the people to use your code....

**Comment by GabrielAssisCode** [comment]
What's the diference between magnet link, info hash and torrent file? Just diferent ways?

**Comment by GabrielAssisCode** [comment]
I'm asking cause I will use and if it's just diferent ways, hash is easier to storage...correct?

**Comment by GabrielAssisCode** [comment]
"connection error to wss://tracker.fastcast.nz" this works with an outside link creator?

**Comment by alxhotel** [comment]
Check out this codepen: https://codepen.io/ferossity/pen/rLxwvv

Also, this workshop might help: https://webtorrent.github.io/workshop

I think this will help you understand better Webtorrent.
