### ISSUE TITLE
Please Add Big green button with link magnet source.

### ISSUE THREAD

**Issue by korenevskiy** [webtorrent/instant.io#236]
1.Please add a large **green button** with the text "**Download TitleName**"( **?&dn=TitleName**) containing the magnet link.
Important point: the button was available immediately after opening the page with magnet in the address
If the hash already exists, you can show the **green button**.
https://instant.io/#magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel
On a similar site, the green button is immediately displayed if there is a hash.
Example:
[https://ivan386.github.io/magnet-converter/#magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel](https://ivan386.github.io/magnet-converter/#magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=wss%3A%2F%2Ftracker.fastcast.nz&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F)

2.And please move LogBlock under video pleyer.
.
_This is necessary for sending links to this page to any people: pensioners, people with disabilities. So that people who do not understand DHT technology can safely use the page to view videos._
.
So that the focus of the active button is initially on the start video viewing button.
Thank you very much for your understanding.

**Comment by feross** [comment]
Thank you for the suggestions. At some point in the future, I'd like to rehaul the design of this site, but I don't have any immediate plans to do so. When the time comes, I'll take your feedback into account. Thanks!
