### ISSUE TITLE
Tracker is apparently down

### ISSUE THREAD

**Issue by YeapGuy** [webtorrent/instant.io#238]
I'm not using the bug report template because it doesn't really fit this case.

I'm getting this error on Chrome and a similar one on Firefox when trying to download a file:
![image](https://user-images.githubusercontent.com/43749899/103815912-5e102480-5064-11eb-9f36-0a42a2d2ce46.png)
The tracker seems to be down, or it's a Cloudflare misconfiguration. Anything you can do about this?

**Comment by alxhotel** [comment]
The tracker seems to be working fine, so I'm closing this issue.

**Comment by paullouisageneau** [comment]
@alxhotel The tracker `tracker.btorrent.xyz` fails for me too, I don't think this should be closed:

![Untitled](https://user-images.githubusercontent.com/600566/105098888-0b465c00-5aab-11eb-9ba6-03b2a13441e3.png)

The actual error is an HTTP 522 (Connection timed out) from Cloudflare.

**Comment by alxhotel** [comment]
Hi @paullouisageneau,

True, I have tested again and it seems the tracker is returning the same error.

However, instant.io still works since it uses more trackers. Ultimately, this error should be reported to BTorrent itself.

So I'm keeping this closed but pinging @DiegoRBaquero.
