### ISSUE TITLE
App is down

### ISSUE THREAD

**Issue by thamaraiselvam** [webtorrent/instant.io#247]
Nothing happens when clicking download button and found this error on console

```
bundle.js:1 WebSocket connection to 'wss://tracker.btorrent.xyz/' failed: 
```

I am not using any adblocker nor extensions, same result on both chrome and firefox latest version

**Comment by thamaraiselvam** [comment]
<img width="695" alt="Screenshot 2021-05-04 at 8 36 26 PM" src="https://user-images.githubusercontent.com/6559664/117025345-76453700-ad18-11eb-9e07-865da9489ff5.png">

**Comment by alxhotel** [comment]
Same as https://github.com/webtorrent/instant.io/issues/254
