### ISSUE TITLE
instant.io not working?

### ISSUE THREAD

**Issue by ghost** [webtorrent/instant.io#254]
[Image of error](https://i.imgur.com/9fuiaun.png)

**What version of this package are you using?**
None I use https://instant.io/ website

**What operating system, Node.js, and npm version?**
Windows 10 Chrome

**What happened?**
When I try to add any magnet link to instant.io I get this error:
WebSocket connection to 'wss://tracker.btorrent.xyz/' failed: 

**What did you expect to happen?**
To Download?
**Are you willing to submit a pull request to fix this bug?**
My code is shit

**Comment by alxhotel** [comment]
Seems this might be due to the trackers being down.

Closing issue

**Comment by akpmohan07** [comment]
Firefox can’t establish a connection to the server at wss://tracker.btorrent.xyz/.
<img width="1344" alt="image" src="https://github.com/webtorrent/instant.io/assets/36654913/66ff130b-1b36-48c8-9dd7-b491cc181944">

**Comment by SilentBot1** [comment]
@akpmohan07 just as a heads up, the tracker wss://tracker.bittorrent.xyz is typically down due to being overloaded and wss://tracker.openwebttorrent.com is [blocked by default](https://github.com/easylist/easylist/issues/18217) by adblockers.

Additionally, the STUN servers configured on instant.io are also down, meaning WebRTC connectivity is patchy if the browser does not insert their own STUN servers.

Only Feross has the ability to fix the main instant.io site and he has been absent for a little while. Due to this, I made a version of instant.io available at https://instant.webtorrent.dev/ which has these issues fixed.

**Comment by nicovoni** [comment]
> @akpmohan07 I made a version of instant.io available at https://instant.webtorrent.dev/ which has these issues fixed.

Hi, I just tried your instance but apparently it doesn't seem to fix the problem:
![image](https://github.com/webtorrent/instant.io/assets/49231283/9a60913a-adcd-458d-94f1-3bc147fc8e53)

**Comment by SilentBot1** [comment]
> > @akpmohan07 I made a version of instant.io available at https://instant.webtorrent.dev/ which has these issues fixed.
> 
> Hi, I just tried your instance but apparently it doesn't seem to fix the problem: ![image](https://private-user-images.githubusercontent.com/49231283/342060663-9a60913a-adcd-458d-94f1-3bc147fc8e53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDIwMDksIm5iZiI6MTcxOTE0MTcwOSwicGF0aCI6Ii80OTIzMTI4My8zNDIwNjA2NjMtOWE2MDkxM2EtYWRjZC00NThkLTk0ZjEtM2JjMTQ3ZmM4ZTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDExMjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMTlmZWMyZTJkMWE5YzFjYTNiNzJkNDljMGYwY2NmMWZhNjQ5N2YyYzM5NTI2NGZiM2VlZDFkMmE4Yzc4M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AphIK5p55bCIjtr1CBja9vKZelfwVPR6QIIIfYQqlxg)

It has an additional tracker added, `wss://tracker.webtorrent.dev`, which does work and is reliable. The other trackers remain and will still throw errors but they sometimes do still work.

**Comment by nicovoni** [comment]
> It has an additional tracker added, `wss://tracker.webtorrent.dev`, which does work and is reliable. The other trackers remain and will still throw errors but they sometimes do still work.

Thanks for the clarification. Unfortunately I am still unable to download the file by opening the torrent file generated by instant.io in any bittorrent client.
![image](https://github.com/webtorrent/instant.io/assets/49231283/7644a76d-180f-46c5-9ad4-66a8cfd6d3fa)

**Comment by SilentBot1** [comment]
> > It has an additional tracker added, `wss://tracker.webtorrent.dev`, which does work and is reliable. The other trackers remain and will still throw errors but they sometimes do still work.
> 
> Thanks for the clarification. Unfortunately I am still unable to download the file by opening the torrent file generated by instant.io in any bittorrent client. ![image](https://private-user-images.githubusercontent.com/49231283/342061369-7644a76d-180f-46c5-9ad4-66a8cfd6d3fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDI5MjUsIm5iZiI6MTcxOTE0MjYyNSwicGF0aCI6Ii80OTIzMTI4My8zNDIwNjEzNjktNzY0NGE3NmQtMTgwZi00NmM1LTlhZDQtNjZhOGNmZDZkM2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDExMzcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMTdhMjZjMWYzNTQwZTkxNjZlOWU1NWIwMjQyNGMwZjQ1MWE2ZjdkNjljNzY5MjFlYjI1NThlY2U2YWIzYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z_p9Bi7zICJnNlXEyYOkggpTI6SOPPgY-f7cck3wCq4)

instant.io is a WebRTC only client, you can only speak with peers which support WebRTC, e.g. other instant.io windows, webtorrent-cli, webtorrent-desktop, webtorrent, or the [torrent](https://github.com/anacrolix/torrent), or experimental builds of other clients using libtorrent (qBittorrent/Deluge).

**Comment by nicovoni** [comment]
> instant.io is a WebRTC only client, you can only speak with peers which support WebRTC, e.g. other instant.io windows, webtorrent-cli, webtorrent-desktop, webtorrent, [torrent](https://github.com/anacrolix/torrent), or experimental builds of other clients using libtorrent (qBittorrent/Deluge).

![image](https://github.com/webtorrent/instant.io/assets/49231283/0948ccc6-6000-45ce-bc15-a47edaad7363)

**Comment by SilentBot1** [comment]
As noted, experimental builds, which you have to build yourself from the master branch of libtorrent. 

You can see your build doesn't support it by the WebTorrent trackers being non-functional.
![image](https://github.com/webtorrent/instant.io/assets/15065825/91c479de-71fd-4755-9762-7d03d6133573)
